### PR TITLE
feat: pwa enhancements 2

### PR DESCRIPTION
**Pull request by userquin**
Add logos for media page and font files on sw precache

### CODE REVIEW

**Comment by userquin** [comment]
Testing on edge with all, on desktop (main page):

imagen

Same but on mobile:

imagen

To fix problems on mobile, some hints:

imagen

**Comment by userquin** [comment]
@davedbase ping

**Comment by davedbase** [comment]
Hmmm, interesting. I'm going to get a stable version of the site up then we can come back this to address properly. @aquaductape any thoughts?

**Comment by aquaductape** [comment]
No comment, this looks fine to me

**Comment by aquaductape** [comment]
@userquin  I'm assuming that this PR should improve mobile score since the screenshot you shared currently reflects the live site

**Comment by userquin** [comment]
@aquaductape no, this PR only add some missing resources to the sw precache to allow work offline.

The screenshots are the result of running the app on localhost with https via `yarn preview-https` script and passing lighthouse on Edge for mobile and desktop.

You can do the same, Lighthouse on chrome is not working right now, see my previous PR for the issue on chrome labs.

**Comment by userquin** [comment]
The optimizations should be applied once analized the result of the test: lighthouse will show you what is the assets that must/can be optimized, if you can do it.

**Comment by davedbase** [comment]
Yeah we have to investigate the perf issue. Thanks so much guys. I'll merge it now.

**Comment by davedbase** [comment]
@userquin thank you so, so much once again. I put your name on our Contributors page: https://www.solidjs.com/contributors. If you'd prefer your full name or just Github name, let me know. =) we use Acknowledgments for extra special callouts of support.

The Solid community thanks you.

**Comment by userquin** [comment]
@davedbase @aquaductape 

If you are not familiar with lighouse, basically it will pass some tests for testing LCP, FCP and so on, also will check rountrips to the server for fetching resources, blocking resources, a11y, best practices (https, compression on resources, http/2).

For mobile it will simulate with a 4x slowdown cpu...

For each entry, you can see some details: for example, on last screenshot for mobile result, you can see what resources can be minified (css styles that are not used, js with unused code: will not hint you what to remove, you must check what can be moved, for example using critters for css, for js you should check your app).

**Comment by davedbase** [comment]
We certainly are familiar, usually a pain in my ass but thanks for the extra details about mobile. =)

**Comment by userquin** [comment]
here some example on a real app (vite 1 + vue 3 from January), the test on development environment on mobile:

imagen

**Pull request merged**
