### PR TITLE
Russian spelling correction

### PR DESCRIPTION
**Pull request by gurugray**
Remove jargon and use more readable phrases

### CODE REVIEW

**Comment by edemaine** [comment]
@TheFedaikin @AdvTechnoKing @pheianox Could one of you review this small PR?

**Review by TheFedaikin — APPROVED** [review]

**Comment by pheianox** [comment]
First, we'd like to thank you for your sincerity and good attention to detail! Thank you very much! And we'd also like you to work on the whole site (e. g. docs), if you're such a fan of digging into the dusty depths of projects

**Comment by AdvTechnoKing** [comment]
Fully endorse this PR :)

**Comment by pheianox** [comment]
To begin with, 
we would like to thank you profoundly 
for the tremendous job you have done! 
Thank you!
Keep up the great work!

**Pull request merged**
