### PR TITLE
perf: add terser-config-atomic

### PR DESCRIPTION
**Pull request by aminya**
This reduces the size of JavaScript by 256 KB

Please test the website to see if everything is OK. For me, it works the same. 

After:

```
Name                               KiloBytes
----                               ---------
_commonjsHelpers.8402d862.js       0.501
404.54eeef4f.js                    0.729
compiler.85657ce1.b226c1ec.js      2509.369
Contributors.5fa30d5e.js           5.185
css.066cb8c2.js                    4.229
css.worker.33906889.fb3dbda2.js    808.713
cssMode.303727e9.js                234.410
Docs.41277864.js                   3.755
editor.worker.3be60899.e9fe25ab.js 87.356
Examples.b3e48c78.js               2.961
formatter.9391ed7f.6ed166d3.js     854.169
Home.885d99bc.js                   13.167
html.9632bd85.js                   4.277
htmlMode.c720328b.js               104.226
index.7f16aa72.js                  47.382
index.7f720a86.js                  0.820
index3.0c9f5b3d.js                 1096.464
javascript.2544f1d7.js             0.823
jsonMode.bbcf0976.js               73.986
Media.32b34459.js                  4.096
monacoTabs.88ecf544.js             1.045
ReplTab.1173c364.js                0.568
setupRepl.07217307.js              19.686
toggleHighContrast.07d696fd.js     2231.236
ts.worker.a079b25f.1e5aed99.js     4368.563
tsMode.2364052c.js                 25.333
Tutorial.73108268.js               153.802
typescript.f80a091d.js             4.792
vendor.3a23317e.js                 47.348
---------------------
Sum size is 12708.9912109375
```

Before:

```
Name                               KiloBytes
----                               ---------
_commonjsHelpers.8402d862.js       0.531
404.6644e62f.js                    0.729
compiler.1f687e20.9a89252a.js      2620.437
Contributors.135618be.js           5.249
css.066cb8c2.js                    4.268
css.worker.1b2305a7.b5192116.js    816.196
cssMode.303727e9.js                240.683
Docs.bb97f463.js                   2.521
editor.worker.030e1be7.285ca7ff.js 88.591
Examples.fea3908d.js               2.947
formatter.3bfd2b78.4e0a09c3.js     868.433
Home.17f083c7.js                   13.218
html.9632bd85.js                   4.326
htmlMode.c720328b.js               107.031
index.338a9fc6.js                  0.629
index.3ebcbb7a.js                  47.111
index3.567124b3.js                 1098.394
javascript.2544f1d7.js             0.823
jsonMode.bbcf0976.js               77.182
Media.4ca49185.js                  4.104
monacoTabs.d5703e45.js             1.039
ReplTab.3d372d67.js                0.568
setupRepl.4076f7f6.js              19.810
toggleHighContrast.07d696fd.js     2253.227
ts.worker.9cb25e38.599d1787.js     4454.137
tsMode.2364052c.js                 26.465
Tutorial.edfa8985.js               153.005
typescript.f80a091d.js             4.817
vendor.277e6d57.js                 48.082
---------------------
Sum size is 12964.5517578125
```

### CODE REVIEW

**Comment by aminya** [comment]
Vite's `?worker` parameter doesn't work nicely with terser-config-atomic because it uses some JavaScript hackery. It defines `new` property, which results in Terser optimizing it into


```ts
import CompilerWorker from 'solid-repl/lib/compiler?worker';
export const compiler = new CompilerWorker();
```

```js
const le = new (()=>new Worker("/assets/compiler.d09e48a5.c835169f.js",{
    type: "module"
}))
```

I need to know why Vite adds add extra `new` around the closure!

**Comment by aminya** [comment]
There is another problem remaining, which seems to cause all the words to be marked as strict. I need to find the code for that and fix it.

image

**Comment by davedbase** [comment]
If the issue still remains I'll hold off merging.

**Comment by aminya** [comment]
Yes, a part of the TypeScript linter relies on bad JavaScript hackery. I need to dive into the solid-repl, and maybe try the optimizations there first. If I find the root cause of it, then we can patch/fix it.

**Comment by modderme123** [comment]
You might try just using the terser unsafe options directly instead of with your terser-config-atomic that way you can disable them one at a time

**Comment by aminya** [comment]
The reserved word issue is resolved now.

**Comment by davedbase** [comment]
Pulled, tested and it worked well. Thanks

**Pull request merged**
