### PR TITLE
docs: adds entry for uplot-solid in ecosystem list

### PR DESCRIPTION
**Pull request by thedanchez**
## Summary

All in the title of the PR -- adds `uplot-solid` to the Ecosystem list.

### CODE REVIEW

**Comment by thedanchez** [comment]
Question about this though -- what are people's thoughts on adding another category called `Data Visualization` that includes all libraries that serve that purpose doing things like charts/plots, data grids, etc? Feels like it would be another helpful bucket that further narrows the set of UI libraries for the Solid ecosystem. I was thinking the following libraries would fall under that umbrella:

- `ag-grid-solid`
- `echarts-solid`
- `uplot-solid`
- `solid-apexcharts`
- `solid-chartjs`

**Comment by davedbase** [comment]
I wouldn't mind that. :)

**Comment by thedanchez** [comment]
> I wouldn't mind that. :)

Awesome -- just updated the PR 👍🏾

**Comment by davedbase** [comment]
Thank you so much! This is great!

**Pull request merged**
