### PR TITLE
feat: pwa enhancements

### LINKED ISSUE #192: pwa enhancement: when testing offline, almost all images do not load
It seems the images on root page when testing offline are missing (also the favicons), you should add them to the sw precache using `includeAssets` option on `VitePWA` plugin configuration:

```ts
// vite.config.ts
const pwaOptions: Partial<VitePWAOptions> = {
  registerType: 'autoUpdate',
  includeAssets: ['assets/*.{png,svg}', 'img/icons/*.png', 'img/favicons/*.png'],
  manifest,
  workbox: {},
};
```

I don't know if there are more directories where you load svg or png images, but you should review it.

imagen

### PR DESCRIPTION
**Pull request by userquin**
This PR includes the icons (png, svg), from public and assets directory, on the sw precache and so working on offline.

I have navigated the app on offline, here some inputs (the screenshoot below, have all errors):

You should review the font file names, there are spaces on some files: you need include them also on sw precache.

~~You should also add `.json` files, the examples pages use them (see screenshot below).~~ DONE

~~You have to include some images on sw precahe from `/public/img/logos` directory, just add the pattern to `assetsInclude` on pwa options.~~ DONE

You're using some external resources (see https://cdn.skypack.dev/solid-js@1.2.3/web on screenshot below), you should follow this entry on pwa docs:

https://vite-plugin-pwa.netlify.app/workbox/generate-ws.html#cache-external-resources

Added `https-localhost` to allow test `pwa` on `https://localhost`, you should test it on Edge or Chromium, on Chrome it is broken: see https://github.com/GoogleChrome/lighthouse/issues/13236

See pwa options on `vite.config.ts` for some hints.

closes #192 

imagen

### CODE REVIEW

**Comment by userquin** [comment]
I suggest you to create an anonymous style on `index.html` to include the icons: see https://cancerdemamadev.fi2net.co/

Open dev tools and check this entry (you should change with your fonts):
```html
<style>
/* montserrat-regular - latin */
    @font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: local('Montserrat Regular'), local('Montserrat-Regular'),
      url('/fonts/montserrat-v15-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('/fonts/montserrat-v15-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
    /* montserrat-500 - latin */
    @font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: local("Montserrat Medium"), local("Montserrat-Medium"),
      url('/fonts/montserrat-v15-latin-500.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('/fonts/montserrat-v15-latin-500.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
    /* montserrat-700 - latin */
    @font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 700;
      font-display: swap;
      src: local('Montserrat Bold'), local('Montserrat-Bold'),
      url('/fonts/montserrat-v15-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('/fonts/montserrat-v15-latin-700.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
    /* montserrat-900 - latin */
    @font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 900;
      font-display: swap;
      src: local('Montserrat Black'), local('Montserrat-Black'),
      url('/fonts/montserrat-v15-latin-900.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('/fonts/montserrat-v15-latin-900.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
    html, body, #app, main, footer {
      font-family: "Montserrat", sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-size: 15px;
    }
    ...
</style>
```

**Comment by userquin** [comment]
I'll add `public/examples/*.json` and `public/logo/**/logo.svg` icons, I'm testing...

**Comment by userquin** [comment]
If you want to use `prompt` strategy, don't forget to updat pwa to `0.11.5` and use the `solid- js` variant ;)

**Comment by userquin** [comment]
I'll add the external resources and so you can forgot the offline support.

**Comment by userquin** [comment]
I cannot make examples working, there are 5 dependencies added, that cannot be added to the sw precache via runtime caching:
- https://unpkg.com/modern-normalize@1.1.0/modern-normalize.css
- https://cdn.skypack.dev/solid-js@1.2.3/web
- https://cdn.skypack.dev/solid-js@1.2.3/store
- https://cdn.skypack.dev/solid-js@1.2.3
- https://cdn.skypack.dev/solid-js@1.2.3/html

I'll push the changes on pwa options.

**Comment by userquin** [comment]
@davedbase  that's all for today , tmr if I have time will review external links...

**Comment by davedbase** [comment]
@userquin thanks! I'm going to merge this in for now. What specifically were you looking at for the external links aspect? Sorry offline PWAs aren't my specialty so your suggestions and comments are *extremely* instructive and helpful.

**Comment by userquin** [comment]
> 
> 
> @userquin thanks! I'm going to merge this in for now. What specifically were you looking at for the external links aspect? Sorry offline PWAs aren't my specialty so your suggestions and comments are _extremely_ instructive and helpful.

run `yarn https-preview` on dev branch (if you run first time will ask for installing the certificate if not yet done), then, open chrome and press f12, go to network tab, then browse to `https://localhost`: wait until the network requests with gears at the begining stops downloading the sw precache, then on the same tab (network), just change No throttling option to offline:

imagen

then navigate the app pages, should work all pages, except tutorial. All pages should also work pressing f5 (do not do a hard refresh Crtl + F5, since will force the browser to go to the server and the dinosaur will appear).

**Comment by modderme123** [comment]
I believe the reason the external urls aren’t working is because they are loaded from a srcdoc iframe: https://github.com/w3c/ServiceWorker/issues/765

**Comment by userquin** [comment]
@modderme123 thx, I'll take a look later, can you point where is the source code here for the iframe?

**Comment by modderme123** [comment]
https://github.com/solidjs/solid-playground/blob/master/src/components/preview.tsx#L194

**Comment by davedbase** [comment]
Oh right, I forgot that the REPL worked this way. @userquin solid-site uses our REPL which I believe supports its own offline mode right now.

**Comment by userquin** [comment]
I was going crazy, I couldn't find a reference in dev!!.

Maybe you can add some `useOnline` module support and enable repl only when online, something similar to `Your browser doesn't support Web Workers` but on `repl` result box.

**Comment by modderme123** [comment]
@davedbase the repl doesn't work offline because the preview pane loads those urls on every edit

**Pull request merged**
