### PR TITLE
Convert site to solid-start

### PR DESCRIPTION
**Pull request by boehs**
closes #261 

Still WIP, **does not currently build**

- [ ] Verify upstream changes
- [ ] Do full site test, ensure everything works
- [ ] Convert to solid-start components?
- [ ] Fix bugs 🐛 

image

Entirely possible the bugs are my fault from a crappy merge, but it's gonna be great

### CODE REVIEW

**Comment by davedbase** [comment]
I can't tell if this is a continuation of the work on https://github.com/solidjs/solid-site/pull/261 or a completely fresh effort.

**Comment by modderme123** [comment]
From the commit history, this looks to be a continuation

**Comment by boehs** [comment]
It's a continuation but it probably won't be for long. Probably going to switch to my own branch but am debugging dependency issues

**Comment by davedbase** [comment]
I was wondering if we could get this moving again? :-)

**Comment by boehs** [comment]
Sure, I might just start from scratch here, if that's ok

**Pull request closed without merging**
